config/routes.rb
Rails.application.routes.draw do
  root to: redirect("/tasks")

  resources :tasks do
    patch :update_status, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true

  enum :status, { incomplete: 0, complete: 1 }

  def toggle_status
    update(status: self.complete? ? :incomplete : :complete)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, except: %i[index create]

  def index
    @tasks = Task.all
    @task = Task.new
  end

  def edit
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("task_name_frame_#{@task.id}", partial: "edit", locals: { task: @task })
      end
    end
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.append("tasks", partial: "task", locals: { task: @task }),
            turbo_stream.update("task_form", partial: "form", locals: { task: Task.new })
          ]
        end
        format.html { redirect_to tasks_path }
      end
    else
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.update("task_form", partial: "form", locals: { task: @task })
        end
        format.html do
          render :index, status: :unprocessable_entity
        end
      end
    end
  end

  def update
    if @task.update(task_params)
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("task_#{@task.id}", partial: "task", locals: { task: @task })
        end
      end
    else
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace("task_#{@task.id}", partial: "task", locals: { task: @task }),
            turbo_stream.update("task_name_frame_#{@task.id}", partial: "edit", locals: { task: @task })
          ]
        end
      end
    end
  end

  def destroy
    @task.destroy

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.remove("task_#{@task.id}")
      end
    end
  end

  def update_status
    respond_to do |format|
      @task.toggle_status

      format.turbo_stream do
        render turbo_stream: turbo_stream.update("task_#{@task.id}", partial: "task", locals: { task: @task })
      end
      format.html { redirect_to tasks_path }
    end
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Todo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="bg-gray-50">
    <main class="max-w-4xl mx-auto my-8">
      <%= yield %>
    </main>
  </body>
</html>

app/views/tasks/_edit.html.erb
<%= form_with model: task, url: task_path(task), class: "flex flex-row gap-2 mr-2", data: { turbo_stream: "task_name_frame_#{task.id}", turbo_method: :patch } do |form| %>
  <%= form.text_field :name, autocomplete: "off", placeholder: "Edite o nome da tarefa", class: "border border-gray-400 rounded-lg bg-gray-50 px-2 flex-1 #{'border-red-600' if task.errors[:name].any?}" %>
  <%= form.button type: :submit, class: "p-2 bg-green-600 text-white rounded-lg hover:bg-green-700 w-10 flex justify-center items-center cursor-pointer" do %>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-5">
      <path fill-rule="evenodd" d="M16.704 4.153a.75.75 0 0 1 .143 1.052l-8 10.5a.75.75 0 0 1-1.127.075l-4.5-4.5a.75.75 0 0 1 1.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 0 1 1.05-.143Z" clip-rule="evenodd" />
    </svg>
  <% end %>
  <% if task.errors.any? %>
    <p class="text-sm pt-1 pl-1 text-red-600"><%= task.errors.full_messages.to_sentence %></p>
  <% end %>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with model: task, url: tasks_path, class: "bg-white shadow rounded-lg p-4 mx-2 lg:mx-0" do |form| %>
  <div class="flex w-full">
    <%= form.text_field :name, placeholder: "Digite o nome da tarefa", autocomplete: "off",
                        class: "border border-gray-400 rounded-lg bg-gray-50 p-2 w-full #{'border-red-600' if task.errors[:name].any?}" %>

    <%= form.submit "Adicionar", class: "bg-green-600 hover:bg-green-800 px-4 rounded-lg font-medium text-white font-lg cursor-pointer ml-4" %>
  </div>

  <% if task.errors.any? %>
    <p class="text-sm pt-1 pl-1 text-red-600"><%= task.errors.full_messages.to_sentence %></p>
  <% end %>
<% end %>

app/views/tasks/_task.html.erb
<%= turbo_frame_tag "task_#{task.id}" do %>
  <div class="bg-white shadow rounded-lg p-2 mx-2 lg:mx-0 flex flex-row mt-2 items-center h-12">
    <div class="inline-flex items-center mx-2">
      <%= form_with model: task, url: update_status_task_path(task), data: { turbo_stream: "task_checkbox_form" } do |form| %>
        <label class="flex items-center cursor-pointer relative">
          <%= form.check_box :status, checked: task.complete?,
                             class: "peer h-5 w-5 cursor-pointer transition-all appearance-none rounded border border-slate-300
                             checked:bg-green-600 checked:border-green-600",
                             onchange: "this.form.requestSubmit()" %>
          <span class="absolute text-white opacity-0 peer-checked:opacity-100 top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-3.5 w-3.5" viewBox="0 0 20 20" fill="currentColor" stroke="currentColor" stroke-width="1">
            <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path>
          </svg>
        </span>
        </label>
      <% end %>
    </div>

    <div class="flex-1">
      <%= turbo_frame_tag "task_name_frame_#{task.id}" do %>
        <p class="<%= "line-through" if task.complete? %>"><%= task.name %></p>
      <% end %>
    </div>

    <div class="flex gap-2">
      <%= link_to edit_task_path(task), data: { turbo_stream: "task_edit_button" } do %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-5 text-gray-600 hover:text-gray-400">
          <path d="m5.433 13.917 1.262-3.155A4 4 0 0 1 7.58 9.42l6.92-6.918a2.121 2.121 0 0 1 3 3l-6.92 6.918c-.383.383-.84.685-1.343.886l-3.154 1.262a.5.5 0 0 1-.65-.65Z" />
          <path d="M3.5 5.75c0-.69.56-1.25 1.25-1.25H10A.75.75 0 0 0 10 3H4.75A2.75 2.75 0 0 0 2 5.75v9.5A2.75 2.75 0 0 0 4.75 18h9.5A2.75 2.75 0 0 0 17 15.25V10a.75.75 0 0 0-1.5 0v5.25c0 .69-.56 1.25-1.25 1.25h-9.5c-.69 0-1.25-.56-1.25-1.25v-9.5Z" />
        </svg>
    <% end %>

      <%= link_to task_path(task), data: { turbo_frame: "task_delete_button", turbo_method: :delete } do %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-5 text-red-600 hover:text-red-800">
          <path fill-rule="evenodd" d="M8.75 1A2.75 2.75 0 0 0 6 3.75v.443c-.795.077-1.584.176-2.365.298a.75.75 0 1 0 .23 1.482l.149-.022.841 10.518A2.75 2.75 0 0 0 7.596 19h4.807a2.75 2.75 0 0 0 2.742-2.53l.841-10.52.149.023a.75.75 0 0 0 .23-1.482A41.03 41.03 0 0 0 14 4.193V3.75A2.75 2.75 0 0 0 11.25 1h-2.5ZM10 4c.84 0 1.673.025 2.5.075V3.75c0-.69-.56-1.25-1.25-1.25h-2.5c-.69 0-1.25.56-1.25 1.25v.325C8.327 4.025 9.16 4 10 4ZM8.58 7.72a.75.75 0 0 0-1.5.06l.3 7.5a.75.75 0 1 0 1.5-.06l-.3-7.5Zm4.34.06a.75.75 0 1 0-1.5-.06l-.3 7.5a.75.75 0 1 0 1.5.06l.3-7.5Z" clip-rule="evenodd"/>
        </svg>
      <% end %>
    </div>
  </div>
<% end %>

app/views/tasks/index.html.erb
<div class="space-y-4">
  <h1 class="font-bold text-4xl mx-2 lg:mx-0">Lista de Tarefas</h1>

  <%= turbo_frame_tag "task_form" do %>
    <%= render "form", task: @task %>
  <% end %>

  <%= turbo_frame_tag "tasks" do %>
    <%= render @tasks %>
  <% end %>
</div>